### ISSUE TITLE
Add `preview path` field in metadata

### ISSUE THREAD

**Issue by Subject38** [Stepland/memon#6]
While the current spec does support specifying a time stamp and length of a preview, it would be nice to also be able to specify a path to a separate music file. Something like:
```json
"preview path": {
"description": "Path to the music preview, relative to the memon file",
"type": "string"
}
```
This would only need to be supported by jujube or any other simulator that implements this format.

**Comment by Stepland** [comment]
I like the idea !

I'll add it in as you suggested and create a `0.3.0` since adding more keys in `metadata` won't break old parsers.

But I'm currently focusing on `1.0.0`, so as a breaking change, what if we use the `preview` field to handle both cases ? I don't see a useful reason to define *both* a preview file *and* a preview time (since backwards compatibility won't be a concern for 1.0.0)
So in 1.0.0 this would be valid :
```json
{
    "preview": "relative/path/to/preview.ogg"
}
```
